export type Step = { n: number; slug: string; title: string; kicker: string; teaching: string[]; practice: string };
export const steps: Step[] = [
  {
    "n": 1,
    "slug": "identify-the-curse",
    "title": "Identify the Curse",
    "kicker": "Name the occupancy. Specificity is mercy.",
    "teaching": [
      "[[img:/images/book/step-1-p185-287.jpg|Step 1: Identify the Curse]]",
      "Your journey to freedom begins with awareness. Before you can take back authority, you must first identify where it was lost or surrendered. This step invites you to slow down and recognize the repetitive cycles that have been playing out in your life. These could be emotional reactions, relationship conflicts, financial lack, or recurring disappointments that seem to follow you no matter how hard you try to change.",
      "You might have found yourself asking questions like:",
      "Why do I always end up in the same kind of difficult relationship?",
      "Why do I keep struggling with money?",
      "Why do I feel unseen or unworthy, even when things are going well?",
      "Every frustration points to a deeper story, a place where authority was released and disorder entered. As you listen, the Holy Spirit will gently reveal the first doorway, perhaps a generational pattern, a childhood wound, an unkept vow, or a moment ruled by fear. As you pause, breathe deeply, tune into His presence, and ask: Holy Spirit, where did this pattern start? Where did I hand over the authority that you intended to be mine?",
      "You may experience a flash memory, a scene from your past, a face, a word, or even a strong emotion. Don’t dismiss it. Often, that moment holds the key to understanding when and how the curse first entered in. Note what comes to mind: sensations, people, situations, emotions. The Spirit will bring clarity as you stay in a posture of listening.",
      "It is vital that you write down everything that surfaces, without judgment or self-censorship. What may seem insignificant— a harsh word, a moment of rejection, or an early failure— can become the seed of a stronghold that has quietly shaped your decisions for decades.",
      "> “For the longest time, I had carried the feeling that my presence disappointed people. When I asked Jesus to show me the entry point for that belief, He revealed an image of my mother in the moment she discovered she was pregnant with me, and she had whispered “Oh no!” under her breath. I was her sixth child, and our family was poor. That single moment had opened a door in the spirit that allowed rejection to take root.”",
      "VIRGINIA— LONDON, UK Remember, you are not uncovering this memory to re-live the pain, but to trace the legal ground the enemy has used to build a fortress in your soul. Once exposed, it begins to lose power, and you gain ground.",
      "If at any point you are struggling to identify the entry point of the curse, don’t panic, just turn to the Strongholds and Legal diagnostic tool is designed to help you.",
      "[[img:/images/book/step-1-p185-290.jpg|Illustration from ORDER]]"
    ],
    "practice": "Name the cycle and the doorway. A date, a name, the whispered sentence where occupancy first entered. Specificity is mercy."
  },
  {
    "n": 2,
    "slug": "reveal-the-stronghold",
    "title": "Reveal the Stronghold",
    "kicker": "Call the structure by its true name.",
    "teaching": [
      "[[img:/images/book/step-2-p188-294.jpg|Step 2: Reveal the Stronghold]]",
      "Once the root of the curse begins to surface, the next step is to name the stronghold that has been built up around it. You are now moving from recognition to revelation, from seeing the doorway to identifying the occupant that entered through it.",
      "In 2 Kings 9, the prophet Jehu confronts Jezebel as not merely a person but a spiritual system. Jezebel represents the stronghold of control, idolatry, manipulation, and counterfeit authority. Her palace had become the headquarters of witchcraft and the center of influence where false power governed a nation. When Jehu declared, “What peace, as long as the harlotries of your mother Jezebel and her witchcraft are so many?”, he was naming the stronghold and detailing the ways in which that oppressive system had ransacked their lives. He discerned that no true peace could exist while that system still ruled.",
      "In the same way, you must ask: What is the “Jezebel” in my palace?",
      "Is it the spirit of fear that governs your decisions?",
      "Is the spirit of lack limiting your generosity?",
      "Perhaps the spirit of rejection filters every relationship through pain and mistrust?",
      "Or is it the spirit of control that compels you to take matters into your own hands instead of trusting God?",
      "It’s not enough to merely feel the pain or frustration, you must name what rules from behind those emotions. Naming the stronghold brings it into the light and strips it of its secrecy and power.",
      "Let’s return to the examples from Step 1:",
      "The person who continually overperforms at work out of fear of being overlooked may discover that the true stronghold isn’t insecurity, it’s control, birthed from rejection. Jezebel has taken her seat in the palace, and control is what keeps her there.",
      "The individual who grew up in poverty and still fears lack might realize that the stronghold is governed by through self-effort rather than divine provision.",
      "The person who fears intimacy after betrayal may find it is the stronghold of Leviathan, the spirit of twisting, that distorts perception and causes mistrust even where safety exists.",
      "When you name the stronghold, you can judge it rightly. You will not be judging people, places, or your past, you will be issuing judgment against a system that has occupied your spiritual territory.",
      "Take time to write down what has been revealed. Name the stronghold clearly. Don’t generalize, be specific, and describe all the ways in which that stronghold has ransacked your life.",
      "It is important to be specific about the consequences of being under the control of this stronghold, because this is the evidence you will use to judge it in Step 5.",
      "For example, you may write:",
      "The stronghold that has produced a deep fear of rejection in me and caused me to strive to perform and control others is governed by Jezebel.",
      "The stronghold that has produced a persistent sense of lack in my life and caused me to be afraid that there is never enough to the point of meanness, is governed by Mammon.",
      "The stronghold that has produced confusion, suspicion, and mistrust so that I have not been able to enjoy healthy relationships, is governed by Leviathan.",
      "As you do this, please understand that you are not condemning yourself; you are diagnosing the intruder so that judgment can take place, and healing and authority can be restored.",
      "> “I realized how much of my authority I had relinquished: areas in my life where I have been a doormat due to control and manipulation, others where I personally have controlled as a mother.”",
      "WOWLIFE CHURCH MEMBER— COLOMBO, SRI LANKA Remember, if you are struggling to reveal the stronghold, you can use the Strongholds and Legal Rights Assessment at the back of the book to shine the light on it, and this time you can go straight to the 32 Legal Rights Checklist if you like.",
      "Once a stronghold has been revealed, it must be dealt with verbally and spiritually. In the next step, you will learn how to confess where you came into agreement with the stronghold, receive the forgiveness which Christ died to give you, and begin restoring divine order through repentance and decree.",
      "[[img:/images/book/step-2-p188-297.jpg|Illustration from ORDER]]"
    ],
    "practice": "Name the structure that sits in the palace — not the symptom. Jezebel, Mammon, Leviathan, or the name the Spirit gives. Then list how it has ransacked you."
  },
  {
    "n": 3,
    "slug": "confess-forgive-repent",
    "title": "Confess, Forgive, & Repent",
    "kicker": "Open the mouth. Release the debt. Turn.",
    "teaching": [
      "[[img:/images/book/step-3-p192-302.jpg|Illustration from ORDER]]",
      "Here, you stand on the threshold between bondage and freedom. Once you have recognized the curse and named the stronghold, the next step is to release its hold on you through confession, forgiveness and repentance. This requires a drivenness, the same divine zeal that moved Jehu to cleanse Jezreel, that drove Jesus into the wilderness and compelled Him to turn over the tables of corruption in the Temple.",
      "Here you will take action. What was once tolerated and covered by silence and lies must now be confronted with truth. Confession exposes what was hidden. Repentance restores divine order where chaos once ruled.",
      "Jehu’s “furious driving” symbolizes the holy urgency needed here and exemplifies the unstoppable force of a soul aligned with divine justice. When Jesus drove out the merchants from the Temple, He was cleansing what belonged to His Father. In the same way, you are cleansing your inner temple, purifying your conscience from the defilement introduced by the whisper of the serpent in the Garden of Eden. The strongholds of Jezebel, Leviathan, and Mammon that once governed through control, slander, and greed can no longer coexist where the truth of Christ now rules.",
      "> “This process has helped me so much. I used to hold on to resentment and hurt, but now I have learned how to let go and find peace again. Submitting, confessing and repenting was not easy at first, but it has really changed me on the inside. I now have more peace in my home and in my heart.”",
      "NANI— SRI LANKA",
      "## CONFESSION AS CLEANSING",
      "To confess is to bring what is hidden into the light, and to say aloud the things you have been hiding: anger, resentment, compromise, guilt, and fear. Do not whisper them internally; speak them out loud. When confession is verbalized, it leaves the private realm of shame and enters the courtroom of truth where God’s mercy rules. Confession is the sacred act of opening hidden spaces to the Spirit’s renewing breath. As you speak what has been concealed, light enters, healing flows, and the heart becomes free again.",
      "Ask the Holy Spirit:",
      "“Where have I agreed with fear, control, or pride?”",
      "“What decisions have I made that reinforced the stronghold?”",
      "“What unrighteous weapons of warfare have I used against others that have caused the enemy to see me as one with him, such as accusation, lying, and coveting?”",
      "Then, as you receive answers, respond with Spirit-inspired action. Replace secrecy with transparency, resentment with blessing, and avoidance with accountability.",
      "Holy Spirit, I confess that I have allowed the fear of lack to shape my thoughts and decisions. I have agreed with the lie that there is not enough, that I must strive, compete, or control in order to survive. I confess that I have trusted my own strength more than Your provision. I have looked to money, people, and circumstances to meet my needs instead of looking to You, my Source.",
      "## FORGIVENESS AS WARFARE",
      "Forgiveness is a legal act of authority within your own soul. It is the moment you entrust every wrong and every hurt to the Father’s perfect justice. In doing so, forgiveness is not sentimental it is just. You are aligning yourself with the Government of Heaven, where God alone settles accounts and declares, Vengeance is Mine. In His mercy, He restores balance, repaying all that was lost and releasing you from every burden of offense. Forgiveness is Heaven’s declaration of completion: It is finished!",
      "The enemy thrives on accusation. Every unresolved bitterness is a foothold he uses to maintain jurisdiction over your emotions. Forgiveness is how you close that door permanently.",
      "Imagine a woman who has carried bitterness toward a parent who constantly criticized her for years. Every time she is corrected by anyone in the present day, she feels attacked and withdraws. The Holy Spirit then shows her that her current overreaction is not related to the present moment, it’s the voice of unforgiveness echoing from her past. She finally forgives her father out loud like this:",
      "Father God, I now see how my dad’s constant criticism made me feel like I was never good enough growing up. This has caused me to be overly defensive, and I find it hard to take correction well. But today, I choose to forgive my dad, and I now release him to you, God.",
      "At last, something shifts; the weight lifts, and peace enters. The spirit of control that once ruled her emotions no longer has legal ground.",
      "Forgiveness doesn’t minimize pain; it transfers jurisdiction. You take the enemy’s accusation and hand it to God, who judges with righteousness.",
      "Father, I forgive [name the person] for [detail the specific act] which [describe the consequences of this in your life]. I now release every accusation and resentment I have carried towards them. I revoke the enemy’s right to use this pain against me anymore. I receive Your peace in its place. Amen.",
      "Forgiveness is the final blow that collapses the stronghold’s foundation. Without it, the walls may fall, but the roots remain. Through forgiveness, every false authority is stripped of power.",
      "## REPENTANCE AS REALIGNMENT",
      "After confession and forgiveness, repentance reinstates your spiritual position. It is the realignment of your life under Heaven’s government, the declaration that you now stand in your rightful authority. Through repentance, you take your place beside Christ, ruling and reigning as a co-heir, advancing His kingdom on earth as it is in Heaven.",
      "Every act of repentance moves you closer to the posture of authority you were created to hold. But it must begin with humility as you bring before God the inner vows, beliefs, and responses shaped by your wounds, and allow Him to replace the lies with truth.",
      "Perhaps you were betrayed and vowed, I will never trust again. Maybe you were abused and resolved, I must always protect myself. These inner agreements, though born in pain, become spiritual covenants that empower the enemy’s logic instead of God’s truth. Repentance is the breaking of those covenants and marks a conscious return to the Government of Heaven.",
      "True repentance stands as a sacred posture before God, where humility meets mercy, and the heart aligns again with Heaven’s order, as David prayed:",
      "> “Have mercy on me, O God, according to Your steadfast love… The sacrifices of God are a broken spirit; a broken and contrite heart, O God, You will not despise.” ||| PSALM 51:1, 17",
      "When we cry, “God have mercy! Christ have mercy!” these are not empty words, they are the cry of the conscience awakening to its need. In that moment, Heaven leans close, and the Spirit witnesses to your heart that you are forgiven. To receive forgiveness is to enter the reality of redemption, the conscience is cleansed, the soul breathes again, and the victory of mercy is established in you.",
      "Having received God’s forgiveness, with full awareness and passion, you can now say: I will never again use the weapon of accusation, against myself, against others, or against God.",
      "## PRAYER OF REPENTANCE AND RESTORATION",
      "> Father of mercy, I come before You with a humble and contrite heart. Thank you for revealing to me the agreements I have made in pain, the inner vows, the judgments, the words I have spoken in fear. I repent of partnering with accusation, control, pride, or unbelief. God have mercy. Christ have mercy. I renounce every lie that has governed my decisions and emotions. I surrender these false agreements to Your judgment and ask that You dissolve their power in the blood of Jesus. I receive Your forgiveness, not as an idea, but as a reality. Let the weight lift now. Let Your mercy flood my heart. I declare that I will",
      "mercy. My heart will hold peace. Restore to me the joy of Your salvation and renew a right spirit within me. From this day forward, I walk in repentance that bears fruit, the fruit of obedience, humility, and authority in Christ. Amen.",
      "Confession and repentance clear the inner temple, and they remove the residue of darkness. But cleansing alone is not the end; it is preparation. The next step is to rebuild, under divine order and alignment. Here you will learn how to stand under God’s covering and take your place within the order of divine authority, where obedience becomes freedom, and submission becomes power.",
      "[[img:/images/book/step-3-p192-305.jpg|Illustration from ORDER]]"
    ],
    "practice": "Write the confession you will speak out loud. Name the person you forgive. Name the inner vow you now break."
  },
  {
    "n": 4,
    "slug": "submit-to-order",
    "title": "Submit to Order",
    "kicker": "Freedom flourishes within structure.",
    "teaching": [
      "[[img:/images/book/step-4-p199-313.jpg|Illustration from ORDER]]",
      "Confession and repentance remove the debris that once clouded your spiritual vision. But freedom without structure leads to confusion. In this next step, you move from cleansing to reordering. You take what was exposed, forgiven, and released, and bring it under divine government.",
      "As we discovered in Part One, when we discussed the theological premise of rank and order, Jehu understood order very well. In 2 Kings 9, Jehu doesn’t merely rebuke Jezebel, he establishes a new order. He commands the messengers of the old regime, saying, “Turn around and follow me.” Jehu understood something that eluded Ahab: authority is not demonstrated by emotion or spectacle, but by command under obedience. Ahab possessed the title of king but surrendered his authority to Jezebel through passivity. Jehu, however, acted with decisiveness because he was under orders.",
      "## MANDATE OVER MANIFESTATION",
      "Just as Jehu’s authority was proven through obedience rather than display, your spiritual gifting and calling are validated through alignment, not applause. The mandate on your life is not centered on personal freedom or recognition, but on the restoration and strengthening of God’s Kingdom through His Church.",
      "The gifts, graces, and anointing that God entrusted to you were never meant for self-promotion or personal validation. They are instruments of service, tools to build the Body of Christ and advance His Kingdom on the earth. When governed by obedience, spiritual power becomes a creative force for transformation; when detached from purpose, it drifts into confusion and disorder.",
      "Many people confuse gifting with authority and assume that a great show of talent, anointing, or supernatural manifestation automatically signals divine approval. But true authority doesn’t flow from what you can do for God, it flows from what you willingly submit to Him. The foundation of Kingdom power is always surrender.",
      "In ministry or leadership, it can be especially tempting to equate power with performance, to rely on visible displays of deliverance, healings, or signs and wonders as proof of calling. Demonstrations fueled by insecurity or fear of rejection may capture human attention, but they fail to move Heaven. When ministry becomes a stage rather than an altar, the enemy recognizes his own reflection, for performance rooted in fear mirrors rebellion, not God’s rest.",
      "Your mandate remains clear: “Seek first the Kingdom of God and His righteousness, and all these things will be added to you.” (Matthew 6:33) You have been entrusted with talents and authority not to elevate yourself, but to build His Kingdom, strengthen His people, and reveal His glory. Freedom is the overflow of alignment, an inheritance that follows obedience.",
      "Jesus embodied this perfectly. In the wilderness, when the devil challenged Him, “If You are the Son of God, command that these stones become bread.” (Matthew 4:3) Jesus refused to act outside the Father’s will. His restraint was His strength. He showed that obedience, not display, is the true mark of sonship.",
      "Likewise, when Joshua encountered the Commander of the Lord’s Army before Jericho, he didn’t rush into battle, trusting in his own experience, he fell down in reverence and asked, “What does my Lord say to His servant?” (Joshua 5:14) From that moment of submission came a divine strategy no human wisdom could have conceived.",
      "When your gifting rests under divine order, your life becomes a channel through which Heaven touches earth, and the Church is strengthened through your obedience.",
      "> “This process has helped me realise that when we are under proper spiritual order— with Christ at the Head— the labour, toil, and unnecessary anxieties fall away.”",
      "SYLVIA— SOUTH AFRICA You’ve completed Step 3, you’ve confessed, repented, forgiven, and received forgiveness. You feel lighter, clearer, and more spiritually alive. Yet after a few weeks, the old patterns begin to creep back in. What happened? You experienced emotional release but not divine order. You felt free, but you did not anchor that freedom under a mandate. Freedom without structure drifts into pride; revelation without obedience can easily turn into rebellion.",
      "To submit to order means to bring every area of your life, your relationships, emotions, finances, time, and calling, under the leadership of God. It is the prayer of alignment and authority that says: Father, in the name of Jesus, I choose Your order. I bring my whole life— my thoughts, decisions, relationships, time, and calling— under the leadership of Your Spirit. I yield my will to Yours, trusting Your wisdom above my own. Lord, align my gifting, my voice, and my actions with Your mandate. Let me move from obedience, not impulse; from Your rest, not striving. Establish Your government in me so that Your peace and authority flow through me without hindrance.",
      "Jesus, You are my Head and my Commander. I follow Your instruction, I respond to Your direction, and I act from the covering of Your order. Let my life be a vessel of alignment, clarity, and stability, strengthening those around me. Where Your order reigns, peace multiplies. Where your alignment is honored, authority is released. I receive that order now, and I choose to walk in it fully. Amen.",
      "This is where genuine authority takes form. When you are rightly aligned with God, you stand in the power He intended for you. Alignment restores dominion— not through force or control, but through partnership with His will. Because you are under His government, He entrusts you with the ability to govern rightly. You are empowered to discern, to judge, and to restore order where chaos exists. This alignment becomes your covering and your protection. Submission doesn’t diminish control; it sanctifies it. It places control in the hands of the One who governs all things well, so that your will becomes an extension of His.",
      "In Step 3, you exposed the trespassers; in Step 4, you return the property to its rightful owner. But this is more than a private act, it is a commissioning. When you live under divine order, you are on divine assignment. You become a representative of Heaven, carrying authority not for personal comfort but for the transformation of others.",
      "Your freedom now becomes service. It strengthens the Church, restores families, and brings light into your workplace and community. The authority you walk in is not yours alone, it flows through you to bless, to heal, and to establish God’s Kingdom wherever you go.",
      "Yet, isolation is the greatest threat to this authority. Many lose their freedom because they refuse accountability. The spirit of independence, which is often mistaken for maturity, isolates the believer from the safety of community. But true authority is never solitary, it is relational. It thrives in alignment with spiritual covering, trusted leaders, and the household of faith. In Part Three: Walking in the Light, we give you details on how to plug into community and remain in intimacy with the Lord, two disciplines that will help keep you in the right order.",
      "[[img:/images/book/step-4-p199-316.jpg|Illustration from ORDER]]"
    ],
    "practice": "Where will this recovered ground live under covering — a pastor, a table, a mandate? Freedom without structure drifts."
  },
  {
    "n": 5,
    "slug": "judge-cast-down-reassign",
    "title": "Judge, Cast Down & Reassign",
    "kicker": "Discernment is a courtroom, not a mood.",
    "teaching": [
      "[[img:/images/book/step-5-p205-323.jpg|Step 5: Judge, Cast Down & Reassign]]",
      "The enemy’s last defense is always to question your legitimacy, but discernment allows you to recognize neutrality and call it into obedience. You call every influence once ruled by the enemy to stand before Christ’s verdict and be reassigned to serve righteousness.",
      "After confession, forgiveness, repentance, and submission, you are now ready to act as a righteous judge under divine authority. This is not about condemning others or yourself, it is about restoring divine order in every realm, including relationships that have been twisted by rebellion, accusation, and fear.",
      "When the enemy senses that judgment is about to be rendered, he resorts to accusation. Every time you rise in authority, the adversary tries to redefine your identity through mockery, fear, or self-doubt. Jezebel looked down from her window and called Jehu by the name, Zimri, which was one that carried the sting of disgrace and illegitimacy.",
      "This is the voice of the accuser. It attacks your character to undermine your commission and seeks to put you back under the same system you are about to overthrow.",
      "It whispers:",
      "“You’re not ready.”",
      "“You’re faking it.”",
      "“You will fail again, just like last time.”",
      "Jehu did not argue, nor did he explain or defend himself. Rather, he lifted his eyes toward the window, toward the place of accusation, and asked, “Who is on my side?” This is the voice of spiritual authority in action. When you know who you are, you stop explaining yourself to the enemy and start mobilizing the atmosphere around you.",
      "## REJECTING THE VOICE OF JEZEBEL",
      "Jehu’s confrontation shows that accusation only has power if you listen to it. He didn’t answer Jezebel, he looked up. That upward gaze is important, for when you stop dialoguing with darkness and lift your focus, when you refuse to respond to an accusation, it loses its grip. To “reject accusation” is to remove the enemy’s right to define your narrative.",
      "After refusing to engage with Jezebel’s accusation, Jehu went on to command the eunuchs who had responded to his call, to cast her down from her seat of authority: “Hashlichu-ha!” Jehu was calling messengers once loyal to Ahab’s corrupt regime to now align under God’s anointed purpose and overthrow the principality that held the whole system in the vice grip of Jezebel’s evil influence.",
      "It is important to note that it is the eunuchs (the marginalized, previously powerless ones) and not Jehu, who enact the judgment. In the same way, when Jesus said, “Get behind Me, Satan!” He was not engaging in an argument or forbidding Satan from tempting him any longer, rather, he was issuing a judicial order and reestablishing the hierarchy.",
      "When you step into this moment, you are reconciling creation back into rank, not fighting darkness. Everything that once served destruction must now serve redemption.",
      "> “I learned to cast down those spirits that affected my life and marriage. Some parts felt uncomfortable because I had to face things from many years ago, but I am grateful I did. I feel lighter, stronger, and closer to God.”",
      "WOWLIFE CHURCH MEMBER— SRI LANKA",
      "## THE STEP 5 PROCESS",
      "In this step, you will: i) Judge the stronghold; ii) Cast it down; and then iii) Reassign it to serve righteousness.",
      "This will confront what once ruled you and bring it under Christ’s authority. Sample prayers are provided to help you navigate each stage with confidence and clarity.",
      "We have included practical examples from the three ruling spirits we’ve previously discussed— Jezebel (control and manipulation), and deception)— to help you understand how to identify, confront, and reassign each one within your own life and spheres of influence. There are, of course, many other entities you may have faced, but these three provide you with an understanding of how to deal with ruling principles in general.",
      "Before you begin, find a quiet place where you can focus without interruption. Take a few deep breaths. Allow your heart to become still and your mind to settle. Welcome the Holy Spirit, the One who searches the heart and reveals the truth, to lead you through every word and revelation that follows.",
      "## JEZEBEL: THE SPIRIT OF CONTROL AND MANIPULATION",
      "## JUDGE THE STRONGHOLD: Identify and Confront",
      "In steps 1 and 2, you noted in your prayer journal the areas in your life, or areas of influence, where the Jezebel spirit gained access through fear, insecurity, and the desire to control outcomes or people. Provided here is a sample prayer that will help you address the curses you identified, and how to address the stronghold they formed so that you can confront it decisively by judging it and reassigning the forces within it to serve God’s purposes through you. Be sure to be explicit and include every single curse and influence the Holy Spirit brought to light:",
      "I recognize the spirit of control and manipulation that has governed my reactions and relationships, through suspicion, impulsive decisions, poor boundaries, intimidation, low self-worth, emotional blackmail, playing the victim, co-dependency, [add to this as the Holy Spirit guides you]. Jezebel, in this way you have set yourself up against the knowledge of God and you have lied about me. You no longer have authority in my life. I command you to stand down and submit to Christ’s dominion. In Jesus’ name. Amen.",
      "## CAST IT DOWN",
      "To cast down means to bring what once ruled you into submission beneath Christ’s feet. Once you have judged the stronghold, you must now remove this influence from the seat of your emotions and decisions:",
      "I cast you down to the ground. I will no longer partner with you to dictate my choices, my leadership, or my identity. I am surrendered to peace, not governed by control. outcomes or people, picture yourself opening your hands, surrendering control, as the weight of manipulation falls away and peace fills its place.",
      "## REASSIGN: Direct it Towards Justice and Restoration",
      "Now that Jezebel’s influence has been judged and brought into divine order, it is time to repurpose what once resisted you. You are now authorized to command every force that once operated under her sway to serve righteousness and advance the purposes of God.",
      "I now reassign the spirits that worked under the control and manipulation of Jezebel in my life to confront and restrict every operation and every system that is against God in my jurisdiction [speak out any specific examples that come to mind]. Suffocate these systems and let the powers that once sought to dominate me now serve the Kingdom of God; close every channel of exploitation and silence the systems that profit from oppression. In Jesus' name, Amen.",
      "Here, the very spirits that once produced control now become instruments of freedom that serve righteousness, under your command as a coheir with Christ.",
      "## MAMMON: THE SPIRIT OF LACK AND FALSE SECURITY",
      "## JUDGE THE STRONGHOLD: Identify and Confront",
      "Begin by addressing the stronghold of Mammon, whom you identified earlier. Speak directly to it with the authority you have received in Christ. stronghold in your life, producing fear, striving, and a spirit of lack, declare aloud:",
      "I recognize that I have lived under the influence of Mammon by hoarding, working compulsively, and planning obsessively; I have developed an inability to rest, a reliance on myself instead of God, and now money feels like survival and generosity feels dangerous, the future feels unsafe, and lack feels like shame, [complete as Holy Spirit guides you]. Mammon, in this way you have set yourself up against the knowledge of God and you have lied about me. You no longer govern me. I command you to stand down and take your proper place under the authority of Christ.",
      "## CAST IT DOWN",
      "Once you have judged the stronghold, you must now remove it from its position of influence: I now cast you down to the ground, beneath the order of Heaven. You will no longer rule my thoughts, my finances, or my emotions. visualize that fear being pulled from its throne and laid before Jesus, who now becomes your true Provider.",
      "## REASSIGN: Direct it Towards Justice and Restoration",
      "Finally, what once worked against you must now serve the Kingdom. Reassign it to bring order, freedom, and restoration in the world.",
      "I now reassign the spirits that worked under the influence of Mammon in my life, to bring down idolatrous economic logics in my areas of influence and ensure they do not survive [speak out any specific examples that come to mind]. I send you into my industry to impoverish greed, endless accumulation, and self-exaltation. I send you to the economy of my city to destroy systems of deceit, corruption, and manipulative trade. Remove from among my people materialism, consumption, and performance-based worth. In Jesus' name, Amen.",
      "This is the full circle of divine governance: what once oppressed you is now commissioned to serve God’s purpose in your life and on the earth.",
      "## LEVIATHAN: THE SPIRIT OF TWISTING AND CONFUSION",
      "## JUDGE THE STRONGHOLD: Identify and Confront",
      "Leviathan operates through distortion, twisting truth, breeding misunderstanding, and turning relationships or communication into knots of confusion. Where you’ve recognized its influence, speak directly with the authority of Christ:",
      "I recognize the presence of Leviathan as the spirit that has twisted truth and sown confusion in my life. Leviathan, I see the way you have twisted thoughts and misinterpreted motives so that neutral comments feel like criticism, correction sounds like rejection, boundaries feel like betrayal, and silence feels like hostility. I recognize your influence in gossip, projections, and assumptions. I see your influence where I have been unnecessarily defensive, overprotective of my ego, and offended in my identity, [complete as Holy Spirit guides you]. Leviathan, in this way, you have set yourself up against the knowledge of God and you have lied about me. You no longer have the power to distort my thoughts or my words. I command you to stand down and take your place under the authority of Christ.",
      "## CAST IT DOWN",
      "You now remove Leviathan from its position of influence in your relationships, communication, and self-perception: I cast you down to the ground, beneath the Government of Heaven. You will no longer twist my discernment, confuse my words, or poison my peace. strained your relationships, visualize those words and moments being straightened, untangled, and aligned under the light of truth.",
      "## REASSIGN: Direct it Toward Justice and Restoration",
      "Command that which once caused confusion, to now serve the work of revelation and reconciliation.",
      "I now reassign the spirits that have worked under the influence of Leviathan in my life to confront the economies of confusion and the systems built on pride in my environment [speak out any specific examples that come to mind]. Bring every web of deceit operating within structures, systems, and patterns of thought into contradiction. Let intellectual towers built on self-exaltation collapse under their own instability. Let false pathways lose their power and let twisted logic unravel before the wisdom of God. Let the power that once twisted truth, twist confusion, manipulation and distortion, until order reigns in the place of confusion. In Jesus' name, Amen.",
      "Through this reassignment, the voice of confusion becomes a servant of truth, and light triumphs where distortion once ruled.",
      "> “The righteous will shine forth as the sun in the kingdom of their Father.” ||| MATTHEW 13:43",
      "Once that area is brought into alignment, it becomes a tool of justice and peace in your surroundings. yourself struggling to know where to send the spirits that you have cast down, we have provided this list of supplementary reassignment prayers at the back of the book.",
      "[[img:/images/book/step-5-p205-326.jpg|Illustration from ORDER]]"
    ],
    "practice": "Write the judgment you issue, the casting down, and where you send what was bound. Not rage. Rank."
  },
  {
    "n": 6,
    "slug": "command-alignment",
    "title": "Command Alignment",
    "kicker": "Speak as one under the King.",
    "teaching": [
      "[[img:/images/book/step-6-p215-337.jpg|Step 6: Command Alignment]]",
      "In the palace, Jezebel still occupied a throne, but her rule carried no true power; it was positional and void of Holy Spirit authority. Those around her, the eunuchs, were neutral. They had served under her but were not loyal to her corruption. Jehu discerned their hesitation and called it forth: “Who is on my side?”",
      "At that question, something shifted. The eunuchs, who had once been silent witnesses, threw Jezebel down. The victory came not through Jehu’s sword but through the obedience of those standing in proximity to corruption. This is a spiritual law: when you discern neutrality and call it to act, Heaven responds. Many battles in your life are waiting for you to do exactly that, to command neutrality to take a side.",
      "Not every force in your life is against you, some are simply neutral. These are the eunuchs at the window, waiting for a command. They represent people, systems, and structures that have remained passive or silent in the presence of disorder.",
      "Ask the Holy Spirit to reveal who or what these neutral forces are in your sphere of influence:",
      "Family lines and relationships that have remained indifferent to truth.",
      "Churches or spiritual communities are caught between conviction and complacency.",
      "Workplaces, schools, or hospitals where integrity has been muted by fear.",
      "Neighborhoods or cities that have settled for peace without justice.",
      "Finances, resources, and bank accounts that have not yet come under Kingdom purpose.",
      "When God reveals them, speak with authority:",
      "Who is on my side? Let righteousness speak! Father, awaken every neutral force, every person, place, and system positioned near influence but bound by silence [list those that the Holy Spirit brings to mind]. Let them rise and cast down everything that exalts itself against Your purpose. I command all that is neutral to align with Heaven’s order and serve Your Kingdom.",
      "Sometimes the “neutral forces” are within your own soul, parts of you that remain undecided, neither believing nor resisting. These are the areas where hesitation and confusion still sit in silence, awaiting leadership. They, too, must be brought into submission to Christ’s truth.",
      "Soul, align with Spirit. Every divided thought, every silent fear, I command you to cast down confusion and exalt the Lordship of Christ within me. Let every part of my being, heart, mind, and will, come into harmony with Heaven’s order.",
      "When the inner world aligns, the outer world responds. Internal peace becomes external authority, and your whole life begins to move in rhythm with the Kingdom of God.",
      "## VICTORY THROUGH ALIGNMENT",
      "> “It’s changed the way I view ‘conflict’ with others, and through this process it’s easier for me to pray into situations rather than expect an outcome change dependent on someone else.”",
      "NATASHA— SRI LANKA Accusation thrives in confusion; order dismantles it. Jehu’s triumph came through the power of alignment; he unified those positioned near Jezebel under one righteous command by casting them down into economies of oppression. Agreement brought victory where confrontation alone could not.",
      "This is the full cycle of Hashlichu-Ha, the sacred act of casting down every thought, influence, and structure that resists divine alignment. Now the atmosphere around you is clear. Then accusations have fallen silent, and every sphere within your reach is being reordered under Christ’s authority. You stand in peace, governed by Heaven, ready to move in dominion.",
      "In the next step, you will testify, declaring what God has done. Your testimony will seal your freedom and extend it outward, turning deliverance into lasting dominion.",
      "[[img:/images/book/step-6-p215-340.jpg|Illustration from ORDER]]"
    ],
    "practice": "Who is on your side? Name the neutral forces — people, systems, parts of your own soul — you now command to align."
  },
  {
    "n": 7,
    "slug": "testify-and-maintain-honor",
    "title": "Testify and Maintain Honor",
    "kicker": "What is occupied must be kept.",
    "teaching": [
      "[[img:/images/book/step-7-p219-345.jpg|Maintain Honor]]",
      "> “This teaching has helped us understand the intuitive reasons we had for stepping away from the church that we once held in high esteem. We spent four years serving in its leadership, and during that time, we came to recognize how control can quietly take root even within good intentions. Stepping away from that structure, in obedience to God’s leading, brought deep freedom and clarity. Today, we walk in our true calling, pursuing God’s will with peace and honor. What once confined us has now become part of our testimony of grace and restoration.”",
      "FEZILE & NKRUMAH MAUNCHO— NAIROBI, KENYA Through testimony, Heaven’s verdict becomes law in your life, and every victory matures into stewardship. This final step transforms spiritual authority into Christlike maturity, to testify is to stand as a witness of divine order restored, giving glory to God while calling all creation into alignment with His Kingdom.",
      "Jehu had accomplished his assignment, Jezebel had fallen, and justice had been executed. Yet his next command was one of respect: “Go, see now this cursed woman, and bury her, for she was a king’s daughter.”",
      "Even though Jezebel embodied corruption and control, Jehu acknowledged her original dignity, she had been born of royal lineage. He did not mock her downfall; he honored her identity. That is the posture of mature authority: honor without compromise.",
      "## RESTORING HONOR AFTER WARFARE",
      "This step invites you to look again, through healed eyes, at the people, places, and institutions that once opposed you or caused pain. You now govern under Christ’s order. To testify with honor means to speak blessing where you once spoke bitterness, to intercede for what once wounded you, and to call forth redemption from what was broken.",
      "## COMMANDING ALIGNMENT THROUGH HONOR",
      "Honor restores dignity to the systems and relationships in your sphere of influence; it transforms their future purpose and does not excuse it. As you testify, use your voice to bless and realign.",
      "Lord, I bless the banks, businesses, and systems within my care. I command financial structures in my sphere to come under divine justice and generosity.",
      "Christ, I honour this person or place as part of Your Kingdom. I release forgiveness and call them into alignment with Your Spirit of truth and love.",
      "All creation belongs to the Lord. I bless the elements of earth, air, fire, and water to align with divine order and serve redemption.",
      "This is the mark of mature authority, when what once resisted you now operates under your covering. Honor becomes your highest form of warfare, because it restores what accusation destroyed.",
      "## Prayer of Honor and Restoration",
      "> Father, I thank You for teaching me Your ways of authority. I now choose honor over mockery, peace over pride. I release forgiveness over every person, place, and system that once opposed me. I command them to come into Kingdom alignment, to serve Your purpose and display Your glory. I bless the institutions, workplaces, churches, and territories within my sphere. I bless even those who once cursed me. Let all things in my domain, seen and unseen, now come under divine order. As a son/daughter of light, I declare that everything entrusted to me shall prosper in righteousness, peace, and joy in the Holy Spirit. In Jesus’ name, Amen.",
      "## Dominion Through Honor",
      "When you can look upon the fallen systems or relationships of your past and say, “Bury her, for she was a king’s daughter.” Your authority has matured from warfare to governance.",
      "This is divine strength clothed in humility, authority ruled by mercy. It distinguishes those who merely cast down from those who rebuild. Honor completes the work of deliverance, turning victory into stewardship.",
      "## THE FULL CIRCLE OF TAKING BACK AUTHORITY",
      "You began this journey by identifying the entry points that gave the enemy access to build strongholds in your life. You have walked through awareness, confession, repentance, and forgiveness. You have come into divine order, pronounced judgment, cast down and reassigned opposition, commanded alignment, and now testified with honor.",
      "## Final Reflection and Commissioning",
      "As you move forward: voice. weight in the Spirit. field of stewardship. but for service.",
      "You are commissioned as a restorer of order, a carrier of peace, and an ambassador of the Kingdom. Go forth in grace, ruling with humility, and building with love.",
      "## Commissioning Decree",
      "> Father, I thank You for restoring me to divine order and positioning me in the fullness of Christ’s authority. I receive the mantle to build, to bless, and to reconcile. My life, my relationships, my work, and every space under my care are now sanctified for Your Kingdom purposes. I commit to walk in peace, govern in love, and steward with humility. I release life wherever I go. Fear, shame, and striving no longer have a claim on me. I reign with Christ— not to control, but to cultivate; not to boast, but to bless. From this day forward, my life becomes a living decree of restoration, authority, and divine order— Your Kingdom come, on earth as it is in Heaven. Amen.",
      "[[img:/images/book/step-7-p219-348.jpg|Illustration from ORDER]]"
    ],
    "practice": "Write the sentence you can say at a table. Then write the blessing over what once opposed you. Honor is how the verdict stays."
  }
];
