/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as FindRouteImport } from './routes/find'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HowRouteImport } from './routes/how'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LightRouteImport } from './routes/light'
import { Route as PathRouteImport } from './routes/path'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StillnessRouteImport } from './routes/stillness'
import { Route as AuthorityIndexRouteImport } from './routes/authority/index'
import { Route as AuthoritySlugRouteImport } from './routes/authority/$slug'
import { Route as BattlefieldIndexRouteImport } from './routes/battlefield/index'
import { Route as BattlefieldSlugRouteImport } from './routes/battlefield/$slug'
import { Route as ExperienceAssessmentRouteImport } from './routes/experience.assessment'
import { Route as ExperienceAuthorityRouteImport } from './routes/experience.authority'
import { Route as ExperienceChambersRouteImport } from './routes/experience.chambers'
import { Route as ExperienceDownloadsRouteImport } from './routes/experience.downloads'
import { Route as ExperienceGlossaryRouteImport } from './routes/experience.glossary'
import { Route as ExperienceHowToUseRouteImport } from './routes/experience.how-to-use'
import { Route as ExperienceJournalRouteImport } from './routes/experience.journal'
import { Route as ExperienceLightRouteImport } from './routes/experience.light'
import { Route as ExperiencePagesRouteImport } from './routes/experience.pages'
import { Route as ExperiencePathRouteImport } from './routes/experience.path'
import { Route as ExperiencePrayersRouteImport } from './routes/experience.prayers'
import { Route as ExperienceSearchRouteImport } from './routes/experience.search'
import { Route as ExperienceStillnessRouteImport } from './routes/experience.stillness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LightRoute = LightRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StillnessRoute = StillnessRouteImport.update({
  id: '/stillness',
  path: '/stillness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/authority/',
  path: '/authority/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritySlugRoute = AuthoritySlugRouteImport.update({
  id: '/authority/$slug',
  path: '/authority/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlefieldIndexRoute = BattlefieldIndexRouteImport.update({
  id: '/battlefield/',
  path: '/battlefield/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlefieldSlugRoute = BattlefieldSlugRouteImport.update({
  id: '/battlefield/$slug',
  path: '/battlefield/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceAssessmentRoute = ExperienceAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceAuthorityRoute = ExperienceAuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceChambersRoute = ExperienceChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceDownloadsRoute = ExperienceDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceGlossaryRoute = ExperienceGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceHowToUseRoute = ExperienceHowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceJournalRoute = ExperienceJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceLightRoute = ExperienceLightRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperiencePagesRoute = ExperiencePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperiencePathRoute = ExperiencePathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperiencePrayersRoute = ExperiencePrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceSearchRoute = ExperienceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceStillnessRoute = ExperienceStillnessRouteImport.update({
  id: '/stillness',
  path: '/stillness',
  getParentRoute: () => ExperienceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/find': typeof FindRoute
  '/glossary': typeof GlossaryRoute
  '/how': typeof HowRoute
  '/introduction': typeof IntroductionRoute
  '/journal': typeof JournalRoute
  '/light': typeof LightRoute
  '/path': typeof PathRoute
  '/prayers': typeof PrayersRoute
  '/print': typeof PrintRoute
  '/purchase': typeof PurchaseRoute
  '/record': typeof RecordRoute
  '/sign-in': typeof SignInRoute
  '/stillness': typeof StillnessRoute
  '/authority/$slug': typeof AuthoritySlugRoute
  '/battlefield/$slug': typeof BattlefieldSlugRoute
  '/experience/assessment': typeof ExperienceAssessmentRoute
  '/experience/authority': typeof ExperienceAuthorityRoute
  '/experience/chambers': typeof ExperienceChambersRoute
  '/experience/downloads': typeof ExperienceDownloadsRoute
  '/experience/glossary': typeof ExperienceGlossaryRoute
  '/experience/how-to-use': typeof ExperienceHowToUseRoute
  '/experience/journal': typeof ExperienceJournalRoute
  '/experience/light': typeof ExperienceLightRoute
  '/experience/pages': typeof ExperiencePagesRoute
  '/experience/path': typeof ExperiencePathRoute
  '/experience/prayers': typeof ExperiencePrayersRoute
  '/experience/search': typeof ExperienceSearchRoute
  '/experience/stillness': typeof ExperienceStillnessRoute
  '/authority/': typeof AuthorityIndexRoute
  '/battlefield/': typeof BattlefieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/find': typeof FindRoute
  '/glossary': typeof GlossaryRoute
  '/how': typeof HowRoute
  '/introduction': typeof IntroductionRoute
  '/journal': typeof JournalRoute
  '/light': typeof LightRoute
  '/path': typeof PathRoute
  '/prayers': typeof PrayersRoute
  '/print': typeof PrintRoute
  '/purchase': typeof PurchaseRoute
  '/record': typeof RecordRoute
  '/sign-in': typeof SignInRoute
  '/stillness': typeof StillnessRoute
  '/authority/$slug': typeof AuthoritySlugRoute
  '/battlefield/$slug': typeof BattlefieldSlugRoute
  '/experience/assessment': typeof ExperienceAssessmentRoute
  '/experience/authority': typeof ExperienceAuthorityRoute
  '/experience/chambers': typeof ExperienceChambersRoute
  '/experience/downloads': typeof ExperienceDownloadsRoute
  '/experience/glossary': typeof ExperienceGlossaryRoute
  '/experience/how-to-use': typeof ExperienceHowToUseRoute
  '/experience/journal': typeof ExperienceJournalRoute
  '/experience/light': typeof ExperienceLightRoute
  '/experience/pages': typeof ExperiencePagesRoute
  '/experience/path': typeof ExperiencePathRoute
  '/experience/prayers': typeof ExperiencePrayersRoute
  '/experience/search': typeof ExperienceSearchRoute
  '/experience/stillness': typeof ExperienceStillnessRoute
  '/authority': typeof AuthorityIndexRoute
  '/battlefield': typeof BattlefieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/find': typeof FindRoute
  '/glossary': typeof GlossaryRoute
  '/how': typeof HowRoute
  '/introduction': typeof IntroductionRoute
  '/journal': typeof JournalRoute
  '/light': typeof LightRoute
  '/path': typeof PathRoute
  '/prayers': typeof PrayersRoute
  '/print': typeof PrintRoute
  '/purchase': typeof PurchaseRoute
  '/record': typeof RecordRoute
  '/sign-in': typeof SignInRoute
  '/stillness': typeof StillnessRoute
  '/authority/$slug': typeof AuthoritySlugRoute
  '/battlefield/$slug': typeof BattlefieldSlugRoute
  '/experience/assessment': typeof ExperienceAssessmentRoute
  '/experience/authority': typeof ExperienceAuthorityRoute
  '/experience/chambers': typeof ExperienceChambersRoute
  '/experience/downloads': typeof ExperienceDownloadsRoute
  '/experience/glossary': typeof ExperienceGlossaryRoute
  '/experience/how-to-use': typeof ExperienceHowToUseRoute
  '/experience/journal': typeof ExperienceJournalRoute
  '/experience/light': typeof ExperienceLightRoute
  '/experience/pages': typeof ExperiencePagesRoute
  '/experience/path': typeof ExperiencePathRoute
  '/experience/prayers': typeof ExperiencePrayersRoute
  '/experience/search': typeof ExperienceSearchRoute
  '/experience/stillness': typeof ExperienceStillnessRoute
  '/authority/': typeof AuthorityIndexRoute
  '/battlefield/': typeof BattlefieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/experience'
    | '/find'
    | '/glossary'
    | '/how'
    | '/introduction'
    | '/journal'
    | '/light'
    | '/path'
    | '/prayers'
    | '/print'
    | '/purchase'
    | '/record'
    | '/sign-in'
    | '/stillness'
    | '/authority/$slug'
    | '/battlefield/$slug'
    | '/experience/assessment'
    | '/experience/authority'
    | '/experience/chambers'
    | '/experience/downloads'
    | '/experience/glossary'
    | '/experience/how-to-use'
    | '/experience/journal'
    | '/experience/light'
    | '/experience/pages'
    | '/experience/path'
    | '/experience/prayers'
    | '/experience/search'
    | '/experience/stillness'
    | '/authority/'
    | '/battlefield/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/experience'
    | '/find'
    | '/glossary'
    | '/how'
    | '/introduction'
    | '/journal'
    | '/light'
    | '/path'
    | '/prayers'
    | '/print'
    | '/purchase'
    | '/record'
    | '/sign-in'
    | '/stillness'
    | '/authority/$slug'
    | '/battlefield/$slug'
    | '/experience/assessment'
    | '/experience/authority'
    | '/experience/chambers'
    | '/experience/downloads'
    | '/experience/glossary'
    | '/experience/how-to-use'
    | '/experience/journal'
    | '/experience/light'
    | '/experience/pages'
    | '/experience/path'
    | '/experience/prayers'
    | '/experience/search'
    | '/experience/stillness'
    | '/authority'
    | '/battlefield'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/experience'
    | '/find'
    | '/glossary'
    | '/how'
    | '/introduction'
    | '/journal'
    | '/light'
    | '/path'
    | '/prayers'
    | '/print'
    | '/purchase'
    | '/record'
    | '/sign-in'
    | '/stillness'
    | '/authority/$slug'
    | '/battlefield/$slug'
    | '/experience/assessment'
    | '/experience/authority'
    | '/experience/chambers'
    | '/experience/downloads'
    | '/experience/glossary'
    | '/experience/how-to-use'
    | '/experience/journal'
    | '/experience/light'
    | '/experience/pages'
    | '/experience/path'
    | '/experience/prayers'
    | '/experience/search'
    | '/experience/stillness'
    | '/authority/'
    | '/battlefield/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  DashboardRoute: typeof DashboardRoute
  ExperienceRoute: typeof ExperienceRouteWithChildren
  FindRoute: typeof FindRoute
  GlossaryRoute: typeof GlossaryRoute
  HowRoute: typeof HowRoute
  IntroductionRoute: typeof IntroductionRoute
  JournalRoute: typeof JournalRoute
  LightRoute: typeof LightRoute
  PathRoute: typeof PathRoute
  PrayersRoute: typeof PrayersRoute
  PrintRoute: typeof PrintRoute
  PurchaseRoute: typeof PurchaseRoute
  RecordRoute: typeof RecordRoute
  SignInRoute: typeof SignInRoute
  StillnessRoute: typeof StillnessRoute
  AuthoritySlugRoute: typeof AuthoritySlugRoute
  BattlefieldSlugRoute: typeof BattlefieldSlugRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
  BattlefieldIndexRoute: typeof BattlefieldIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light': {
      id: '/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stillness': {
      id: '/stillness'
      path: '/stillness'
      fullPath: '/stillness'
      preLoaderRoute: typeof StillnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/authority'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/$slug': {
      id: '/authority/$slug'
      path: '/authority/$slug'
      fullPath: '/authority/$slug'
      preLoaderRoute: typeof AuthoritySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlefield/': {
      id: '/battlefield/'
      path: '/battlefield'
      fullPath: '/battlefield/'
      preLoaderRoute: typeof BattlefieldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlefield/$slug': {
      id: '/battlefield/$slug'
      path: '/battlefield/$slug'
      fullPath: '/battlefield/$slug'
      preLoaderRoute: typeof BattlefieldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/assessment': {
      id: '/experience/assessment'
      path: '/assessment'
      fullPath: '/experience/assessment'
      preLoaderRoute: typeof ExperienceAssessmentRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/authority': {
      id: '/experience/authority'
      path: '/authority'
      fullPath: '/experience/authority'
      preLoaderRoute: typeof ExperienceAuthorityRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/chambers': {
      id: '/experience/chambers'
      path: '/chambers'
      fullPath: '/experience/chambers'
      preLoaderRoute: typeof ExperienceChambersRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/downloads': {
      id: '/experience/downloads'
      path: '/downloads'
      fullPath: '/experience/downloads'
      preLoaderRoute: typeof ExperienceDownloadsRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/glossary': {
      id: '/experience/glossary'
      path: '/glossary'
      fullPath: '/experience/glossary'
      preLoaderRoute: typeof ExperienceGlossaryRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/how-to-use': {
      id: '/experience/how-to-use'
      path: '/how-to-use'
      fullPath: '/experience/how-to-use'
      preLoaderRoute: typeof ExperienceHowToUseRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/journal': {
      id: '/experience/journal'
      path: '/journal'
      fullPath: '/experience/journal'
      preLoaderRoute: typeof ExperienceJournalRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/light': {
      id: '/experience/light'
      path: '/light'
      fullPath: '/experience/light'
      preLoaderRoute: typeof ExperienceLightRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/pages': {
      id: '/experience/pages'
      path: '/pages'
      fullPath: '/experience/pages'
      preLoaderRoute: typeof ExperiencePagesRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/path': {
      id: '/experience/path'
      path: '/path'
      fullPath: '/experience/path'
      preLoaderRoute: typeof ExperiencePathRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/prayers': {
      id: '/experience/prayers'
      path: '/prayers'
      fullPath: '/experience/prayers'
      preLoaderRoute: typeof ExperiencePrayersRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/search': {
      id: '/experience/search'
      path: '/search'
      fullPath: '/experience/search'
      preLoaderRoute: typeof ExperienceSearchRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/stillness': {
      id: '/experience/stillness'
      path: '/stillness'
      fullPath: '/experience/stillness'
      preLoaderRoute: typeof ExperienceStillnessRouteImport
      parentRoute: typeof ExperienceRoute
    }
  }
}

interface ExperienceRouteChildren {
  ExperienceAssessmentRoute: typeof ExperienceAssessmentRoute
  ExperienceAuthorityRoute: typeof ExperienceAuthorityRoute
  ExperienceChambersRoute: typeof ExperienceChambersRoute
  ExperienceDownloadsRoute: typeof ExperienceDownloadsRoute
  ExperienceGlossaryRoute: typeof ExperienceGlossaryRoute
  ExperienceHowToUseRoute: typeof ExperienceHowToUseRoute
  ExperienceJournalRoute: typeof ExperienceJournalRoute
  ExperienceLightRoute: typeof ExperienceLightRoute
  ExperiencePagesRoute: typeof ExperiencePagesRoute
  ExperiencePathRoute: typeof ExperiencePathRoute
  ExperiencePrayersRoute: typeof ExperiencePrayersRoute
  ExperienceSearchRoute: typeof ExperienceSearchRoute
  ExperienceStillnessRoute: typeof ExperienceStillnessRoute
}

const ExperienceRouteChildren: ExperienceRouteChildren = {
  ExperienceAssessmentRoute: ExperienceAssessmentRoute,
  ExperienceAuthorityRoute: ExperienceAuthorityRoute,
  ExperienceChambersRoute: ExperienceChambersRoute,
  ExperienceDownloadsRoute: ExperienceDownloadsRoute,
  ExperienceGlossaryRoute: ExperienceGlossaryRoute,
  ExperienceHowToUseRoute: ExperienceHowToUseRoute,
  ExperienceJournalRoute: ExperienceJournalRoute,
  ExperienceLightRoute: ExperienceLightRoute,
  ExperiencePagesRoute: ExperiencePagesRoute,
  ExperiencePathRoute: ExperiencePathRoute,
  ExperiencePrayersRoute: ExperiencePrayersRoute,
  ExperienceSearchRoute: ExperienceSearchRoute,
  ExperienceStillnessRoute: ExperienceStillnessRoute,
}

const ExperienceRouteWithChildren = ExperienceRoute._addFileChildren(
  ExperienceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AssessmentRoute: AssessmentRoute,
  DashboardRoute: DashboardRoute,
  ExperienceRoute: ExperienceRouteWithChildren,
  FindRoute: FindRoute,
  GlossaryRoute: GlossaryRoute,
  HowRoute: HowRoute,
  IntroductionRoute: IntroductionRoute,
  JournalRoute: JournalRoute,
  LightRoute: LightRoute,
  PathRoute: PathRoute,
  PrayersRoute: PrayersRoute,
  PrintRoute: PrintRoute,
  PurchaseRoute: PurchaseRoute,
  RecordRoute: RecordRoute,
  SignInRoute: SignInRoute,
  StillnessRoute: StillnessRoute,
  AuthoritySlugRoute: AuthoritySlugRoute,
  BattlefieldSlugRoute: BattlefieldSlugRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
  BattlefieldIndexRoute: BattlefieldIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
